language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25

script:
   - ./gradlew build connectedCheck
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &